name: Building UI Service PipeLine
on:
  pull_request:
    branches:
      - dev
      - main
      - master
      - qa
      - staging
      - 'feature-*'
  push:
    branches:
      - main
      - master
      - 'feature-*'
      - '!releases/**-alpha'
      - 'feature/*'
      - testcases
  workflow_dispatch:

env:
  TEST_BUCKET: subham-dev
  REPO_NAME: "${{ github.event.repository.name }}"

permissions:
 id-token: write
 contents: read
 actions: read
 security-events: write

jobs:
  build:
    name: BuildAndPush
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Export Env Vars
      run: |
        BRANCH_NAME="${GITHUB_REF##*/}"
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
        echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
            
    - name: Check any Leaked Secrets
      uses: gitleaks/gitleaks-action@v2.3.4
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        GITLEAKS_ENABLE_COMMENTS: 'true'
        GITLEAKS_NOTIFY_USER_LIST: '@smandal-tharkka'
